# Corp: Fast Shop S. A.
# Maintener: Ricardo Peroto - tjoserp@estabilis.com
# Maintener: Daniel Gines - daniel@estabilis.com
# Organização: Estabilis

variables:
  FORCE_COLOR: "1" # para ficar bonito no terminal \o/
  ENVIRONMENT: $CI_COMMIT_REF_NAME # Controlará os ambientes

stages:
  - angular-build
  - deployment
  - deployment-qa
  - deployment-prod

angular-inspection:
  stage: angular-build
  image: node:12
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    paths:
      - dist/
  cache:
    key: $CI_COMMIT_SHA
    paths:
      - dist/
      - node_modules/
  services:
      - name: docker:dind
  before_script:
    - npm install --silent
    - npm i -g @angular-devkit/build-angular@0.803.21
    - npm i -g @angular/cli@8.3.21
    - npm i -g @angular/common@8.2.14
    - npm i -g ngx-cookie-service 
    - ng version
  script:
     - ng build --configuration=local
  tags:
    - gitlab-runner-docker01
  only:
    - /feature\/.*/
    - /fix\/.*/
    - /hotfix\/.*/

angular-build:
  stage: angular-build
  image: node:latest
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    paths:
      - dist/
  cache:
    key: $CI_COMMIT_SHA
    paths:
      - dist/
  services:
      - name: docker:dind
  before_script:
    - npm install
    - npm i -g @angular-devkit/build-angular
    - npm i -g @angular/cli
    - ng version 
  script:
     - if [[ $ENVIRONMENT =~ ^qa.* ]]; then ENVIRONMENT=qa; fi; 
     - ng build --configuration=$ENVIRONMENT  
  tags:
    - gitlab-runner-docker01
  only:
    - develop
    - master
    - staging
    - /qa\/.*/ 

deployment-dev:  
  stage: deployment
  image: ubuntu:latest
  before_script:
    - apt-get update && apt install curl -y && apt install zip -y
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - aws --version
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID_DEV;
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_DEV;
  script:
    - aws s3 cp dist/ s3://promotion-management-develop.fastshop.com.br --recursive
  tags:
    - gitlab-runner-docker01
  only:
    - develop

deployment-qa:
  stage: deployment-qa
  image: ubuntu:latest
  before_script:
    - apt-get update && apt install curl -y && apt install zip -y
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - aws --version
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID_DEV;
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY_DEV;
  script:
    - aws s3 cp dist/ s3://promotion-management-qa.fastshop.com.br --recursive
  tags:
    - gitlab-runner-docker01
  only:
    - /qa\/.*/
  environment:
    name: qa
  when: manual
  
deployment:
  stage: deployment-prod
  image: ubuntu:latest
  before_script:
    - apt-get update && apt install curl -y && apt install zip -y
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip awscliv2.zip
    - ./aws/install
    - aws --version
    - aws configure set aws_access_key_id $ID_MASTER;
    - aws configure set aws_secret_access_key $SECRET_MASTER;
  script:
    - aws s3 cp dist/ s3://promotion-management.fastshop.com.br --recursive
  tags:
    - gitlab-runner-docker01
  only:
    - master
