# Corp: Fast Shop S. A.
# Maintener: Ricardo Peroto - tjoserp@estabilis.com
# Maintener: Daniel Gines - daniel@estabilis.com
# Organização: Estabilis

variables:
  FORCE_COLOR: "1" # para ficar bonito no terminal \o/
  ENVIRONMENT: $CI_COMMIT_REF_NAME # Controlará os ambientes

stages:
  - angular-build
  - deployment
  - deployment-qa

angular-inspection:
  stage: angular-build
  image: node:10
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    paths:
      - dist/
  cache:
    key: $CI_COMMIT_SHA
    paths:
      - dist/
      - node_modules/
  services:
      - name: docker:dind
  before_script:
    - npm install --silent
    - npm i -g @angular-devkit/build-angular@0.800.6
    - npm i -g @angular/cli@8.0.6
    - ng version
  script:
     - ng build --configuration=$ENVIRONMENT --aot --build-optimizer
  tags:
    - gitlab-runner-docker01
  only:
    - /feature\/.*/
    - /fix\/.*/
    - /hotfix\/.*/
    - merge_requests

angular-build:
  stage: angular-build
  image: node:10
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    when: always
    paths:
      - dist/
  cache:
    key: $CI_COMMIT_SHA
    paths:
      - dist/
  services:
      - name: docker:dind
  before_script:
    - npm install --silent
    - npm i -g @angular-devkit/build-angular@0.800.6
    - npm i -g @angular/cli@8.0.6
    - ng version 
  script:
     - if [[ $ENVIRONMENT =~ ^qa.* ]]; then ENVIRONMENT=qa; fi; 
     - ng build --configuration=$ENVIRONMENT --aot --build-optimizer  
  tags:
    - gitlab-runner-docker01
  only:
    - develop
    - master
    - staging
    - /qa\/.*/ 

deployment-dev:  
  stage: deployment
  before_script:
# $CI_COMMIT_REF_NAME == "develop" # Valor do artefato.
    - set aws_access_key_id $AWS_ACCESS_KEY_ID;
    - set aws_secret_access_key_id $AWS_SECRET_ACCESS_KEY;
  script:
    - aws s3 cp dist/* s3://promotion-management-develop.fastshop.com.br --recursive
  tags:
    - gitlab-runner-shell01
  only:
    - develop
    - /feature\/.*/

deployment-qa:
  stage: deployment-qa
  before_script:
    - set aws_access_key_id $AWS_ACCESS_KEY_ID;
    - set aws_secret_access_key_id $AWS_SECRET_ACCESS_KEY;
  script:
    - aws s3 cp dist/* s3://promotion-management-qa.fastshop.com.br --recursive
  tags:
    - gitlab-runner-shell01
  only:
    - /qa\/.*/
  environment:
    name: qa
  when: manual


